### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Stoupe** [Stoupe/gpt-chat-app#1]
### Features
- [x] User-editable system message
- [x] Ability to switch between GPT3 and GPT4
  - [ ] Save which model was used in the message and display to user 
- [ ] Rename chats
  - [ ] Auto-name by summarising the conversation
  - [ ] Manually name/rename chats
- [ ] Encrypt API keys
- [ ] Polish UI more
  - [ ] No indication things are happening with buttons are clicked
  - [ ] Streamed text is a bit janky, this should appear as if it's being typed
- [ ] Nicer homepage
  - [ ] When logged in
    - [ ] With existing chats
    - [ ] Without existing chats
  - [ ] When logged out

### Bugs
- [x] Fix code blocks causing horizontal scroll
- [ ] *(partially working)* Code blocks colour syntax highlighting not working
- [ ] Bad experience when a user doesn't have an API key (500 error)
- [x] Chats not saved in global state when going between chats, refetch is needed every time
- [ ] Textarea input is still a bit janky
- [ ] Editing system message will always create a new chat message

### Other
- [ ] Update readme
